- hosts: all
  remote_user: ec2-user
  become: yes
  tasks: 
  - name: installing Apache
    yum:
      name: httpd
      state: present
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
  - name: Copy index file to remote location
    copy:
      src: /home/ec2-user/index.html
      dest: /var/www/html
      
