- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Print the gateway for each host when defined
    ansible.builtin.debug:
      msg: HI chief username is {{uname}} and my password is {{passd}}
      